name: CI
on: [push, pull_request]

env:
  CI: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [ 1.13.x, 1.14.x, 1.15.x ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2
      - run: go test ./...
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15.x
      - uses: actions/checkout@v2
      - run: go get honnef.co/go/tools/cmd/staticcheck@v0.2.2
      - run: make check
